### ISSUE TITLE
Database Credentials Issue

### ISSUE THREAD

**Issue by karthikya** [karthikrocks/Website1#1]
Calling the database in every function is quite hard. It is basically hardcoding.

Solution 1 - create new server and store Database Credentials there.

Solution 2 - Store Database Credentials in built in Flask module. 
![diagram](https://user-images.githubusercontent.com/69461837/121639539-4cff8f80-caaa-11eb-94e6-765b16793eec.png)

**Comment by karthikrocks** [comment]
This issue is closed, fixed take a look at app.py
